// Generated by Framer (b62c1c2)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    getPropertyControls,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Iconoir
} from "https://framerusercontent.com/modules/zL9598C4KbEbqUGvSR14/rI8sPHpnG9XGcCPc0vU4/Iconoir.js";
import * as sharedStyle from "https://framerusercontent.com/modules/cDNlCnmrd1AWIzgLMLvZ/AkE2krK0mv5S37ZsfdFx/nvEuWzqIx.js";
const IconoirFonts = getFonts(Iconoir);
const IconoirControls = getPropertyControls(Iconoir);
const cycleOrder = ["eNWvs9Bok", "wiFPO1285"];
const serializationHash = "framer-rmsNA";
const variantClassNames = {
    eNWvs9Bok: "framer-v-1ltxx24",
    wiFPO1285: "framer-v-13k3fbr"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "eNWvs9Bok",
    Phone: "wiFPO1285"
};
const getProps = ({
    color,
    height,
    icon,
    id,
    text,
    width,
    ...props
}) => {
    return { ...props,
        IXf94UmrM: color ? ? props.IXf94UmrM ? ? "var(--token-3eeeadcf-7a3a-42f2-9a6c-47f4d4eb10dd, rgb(78, 82, 85))",
        nQai827XS: icon ? ? props.nQai827XS ? ? "ClockOutline",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "eNWvs9Bok",
        YYmLlT788: text ? ? props.YYmLlT788 ? ? "1 hr 24 mins"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        YYmLlT788,
        nQai827XS,
        IXf94UmrM,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "eNWvs9Bok",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ltxx24", className, classNames),
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "eNWvs9Bok",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        wiFPO1285: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        background: {
                            alt: "",
                            fit: "fill"
                        },
                        className: "framer-18j2dx4",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "TbA2RRd26",
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1qdmz2z-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "envo8q2uJ-container",
                                nodeId: "envo8q2uJ",
                                rendersWithMotion: true,
                                scopeId: "mq36gyiyj",
                                children: /*#__PURE__*/ _jsx(Iconoir, {
                                    color: IXf94UmrM,
                                    height: "100%",
                                    iconSearch: "Home",
                                    iconSelection: nQai827XS,
                                    id: "envo8q2uJ",
                                    layoutId: "envo8q2uJ",
                                    mirrored: false,
                                    selectByList: true,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-gsxb31",
                                "data-styles-preset": "nvEuWzqIx",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-IXf94UmrM-mq36gyiyj))"
                                },
                                children: "1 hr 24 mins"
                            })
                        }),
                        className: "framer-cvsa2p",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "QZ7wTaVEE",
                        style: {
                            "--extracted-r6o4lv": "var(--variable-reference-IXf94UmrM-mq36gyiyj)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-IXf94UmrM-mq36gyiyj": IXf94UmrM
                        },
                        text: YYmLlT788,
                        verticalAlignment: "center",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rmsNA.framer-1d8k85n, .framer-rmsNA .framer-1d8k85n { display: block; }", ".framer-rmsNA.framer-1ltxx24 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-rmsNA .framer-18j2dx4 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }", ".framer-rmsNA .framer-1qdmz2z-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }", ".framer-rmsNA .framer-cvsa2p { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-rmsNA.framer-1ltxx24 { gap: 0px; } .framer-rmsNA.framer-1ltxx24 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-rmsNA.framer-1ltxx24 > :first-child { margin-left: 0px; } .framer-rmsNA.framer-1ltxx24 > :last-child { margin-right: 0px; } }", ".framer-rmsNA.framer-v-13k3fbr.framer-1ltxx24 { gap: 4px; }", ".framer-rmsNA.framer-v-13k3fbr .framer-18j2dx4 { height: var(--framer-aspect-ratio-supported, 16px); width: 16px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-rmsNA.framer-v-13k3fbr.framer-1ltxx24 { gap: 0px; } .framer-rmsNA.framer-v-13k3fbr.framer-1ltxx24 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-rmsNA.framer-v-13k3fbr.framer-1ltxx24 > :first-child { margin-left: 0px; } .framer-rmsNA.framer-v-13k3fbr.framer-1ltxx24 > :last-child { margin-right: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 109
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"wiFPO1285":{"layout":["auto","auto"]}}}
 * @framerVariables {"YYmLlT788":"text","nQai827XS":"icon","IXf94UmrM":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const Framermq36gyiyj = withCSS(Component, css, "framer-rmsNA");
export default Framermq36gyiyj;
Framermq36gyiyj.displayName = "Episode/List Item";
Framermq36gyiyj.defaultProps = {
    height: 24,
    width: 109
};
addPropertyControls(Framermq36gyiyj, {
    variant: {
        options: ["eNWvs9Bok", "wiFPO1285"],
        optionTitles: ["Default", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    YYmLlT788: {
        defaultValue: "1 hr 24 mins",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    },
    nQai827XS: IconoirControls ? .["iconSelection"] && { ...IconoirControls["iconSelection"],
        defaultValue: "ClockOutline",
        description: undefined,
        hidden: undefined,
        title: "Icon"
    },
    IXf94UmrM: {
        defaultValue: 'var(--token-3eeeadcf-7a3a-42f2-9a6c-47f4d4eb10dd, rgb(78, 82, 85)) /* {"name":"General Paragraph"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(Framermq36gyiyj, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...IconoirFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framermq36gyiyj",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"wiFPO1285\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "109",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "24",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"YYmLlT788\":\"text\",\"nQai827XS\":\"icon\",\"IXf94UmrM\":\"color\"}",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}