// Generated by Framer (eca4804)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["GF;Public Sans-regular", "GF;Public Sans-700", "GF;Public Sans-700italic", "GF;Public Sans-italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Public Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/publicsans/v18/ijwGs572Xtc6ZYQws9YVwllKVG8qX1oyOymuFpm5xg0pX189fg.woff2",
        weight: "400"
    }, {
        family: "Public Sans",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/publicsans/v18/ijwGs572Xtc6ZYQws9YVwllKVG8qX1oyOymu8Z65xg0pX189fg.woff2",
        weight: "700"
    }, {
        family: "Public Sans",
        source: "google",
        style: "italic",
        url: "https://fonts.gstatic.com/s/publicsans/v18/ijwAs572Xtc6ZYQws9YVwnNDZpDyNjGolS673tq2hwcofVotfj7j.woff2",
        weight: "700"
    }, {
        family: "Public Sans",
        source: "google",
        style: "italic",
        url: "https://fonts.gstatic.com/s/publicsans/v18/ijwAs572Xtc6ZYQws9YVwnNDZpDyNjGolS673tpRgAcofVotfj7j.woff2",
        weight: "400"
    }]
}];
export const css = ['.framer-iPz3u .framer-styles-preset-gsxb31:not(.rich-text-wrapper), .framer-iPz3u .framer-styles-preset-gsxb31.rich-text-wrapper p { --framer-font-family: "Public Sans", "Public Sans Placeholder", sans-serif; --framer-font-family-bold: "Public Sans", "Public Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Public Sans", "Public Sans Placeholder", sans-serif; --framer-font-family-italic: "Public Sans", "Public Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.04em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-3eeeadcf-7a3a-42f2-9a6c-47f4d4eb10dd, #4e5255); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
export const className = "framer-iPz3u";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}