// Generated by Framer (74b1a33)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    getLoadingLazyAtYPosition,
    Image,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/cDNlCnmrd1AWIzgLMLvZ/AkE2krK0mv5S37ZsfdFx/nvEuWzqIx.js";
const serializationHash = "framer-Zswun";
const variantClassNames = {
    mQZfDt1ZP: "framer-v-1miub5v"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .4,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    text,
    width,
    ...props
}) => {
    return { ...props,
        th7Tdcw3U: text ? ? props.th7Tdcw3U ? ? "Personalized playlists"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        th7Tdcw3U,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "mQZfDt1ZP",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1miub5v", className, classNames),
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "mQZfDt1ZP",
                    ref: ref ? ? ref1,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "Icon",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 24) - 0 - 24) / 2)),
                            pixelHeight: 24,
                            pixelWidth: 24,
                            src: "https://framerusercontent.com/images/h1wnzKUFiG9E6ojDdiZ9yhMUs28.svg"
                        },
                        className: "framer-lnxf9w",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "Vws9TPNmN"
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-gsxb31",
                                "data-styles-preset": "nvEuWzqIx",
                                children: "Personalized playlists"
                            })
                        }),
                        className: "framer-1h3tqqn",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "yYXWtf7v5",
                        style: {
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: th7Tdcw3U,
                        verticalAlignment: "center",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Zswun.framer-nwdwt0, .framer-Zswun .framer-nwdwt0 { display: block; }", ".framer-Zswun.framer-1miub5v { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 185px; }", ".framer-Zswun .framer-lnxf9w { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); overflow: hidden; position: relative; width: 24px; }", ".framer-Zswun .framer-1h3tqqn { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Zswun.framer-1miub5v { gap: 0px; } .framer-Zswun.framer-1miub5v > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-Zswun.framer-1miub5v > :first-child { margin-left: 0px; } .framer-Zswun.framer-1miub5v > :last-child { margin-right: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 185
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"th7Tdcw3U":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerRBbULoh99 = withCSS(Component, css, "framer-Zswun");
export default FramerRBbULoh99;
FramerRBbULoh99.displayName = "Feature List Item";
FramerRBbULoh99.defaultProps = {
    height: 24,
    width: 185
};
addPropertyControls(FramerRBbULoh99, {
    th7Tdcw3U: {
        defaultValue: "Personalized playlists",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    }
});
addFonts(FramerRBbULoh99, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerRBbULoh99",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "185",
                "framerVariables": "{\"th7Tdcw3U\":\"text\"}",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "24"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}