// Generated by Framer (cf4c6d7)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-YvqMJ .framer-styles-preset-1s2pxue:not(.rich-text-wrapper), .framer-YvqMJ .framer-styles-preset-1s2pxue.rich-text-wrapper a { --framer-link-current-text-decoration: underline; --framer-link-hover-text-decoration: none; --framer-link-text-decoration: none; }"];
export const className = "framer-YvqMJ";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}