// Generated by Framer (6ca5d98)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 12.75 0 C 11.093 0 9.75 1.343 9.75 3 C 9.75 1.343 8.407 0 6.75 0 L 0 0 L 0 13.5 L 6.75 13.5 C 8.407 13.5 9.75 14.843 9.75 16.5 C 9.75 14.843 11.093 13.5 12.75 13.5 L 19.5 13.5 L 19.5 0 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="16.5px" id="VaJ0SXoYw" transform="translate(2.25 5.25)" width="19.5px"/><path d="M 0 3 C 0 1.343 1.343 0 3 0 L 9.75 0 L 9.75 13.5 L 3 13.5 C 1.343 13.5 0 14.843 0 16.5" fill="transparent" height="16.5px" id="oAakIlfTx" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12 5.25)" width="9.75px"/><path d="M 0 13.5 L 6.75 13.5 C 8.407 13.5 9.75 14.843 9.75 16.5 L 9.75 3 C 9.75 1.343 8.407 0 6.75 0 L 0 0 Z" fill="transparent" height="16.5px" id="imv5_mFb8" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.25 5.25)" width="9.75px"/></svg>';
const getProps = ({
    alpha,
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: color ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)",
        lschgej4H: width1 ? ? props.lschgej4H ? ? 1.5,
        qxTvv_EBh: alpha ? ? props.qxTvv_EBh
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        lschgej4H,
        qxTvv_EBh,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("1523066278", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-0nw0H", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m6trwb": qxTvv_EBh,
            "--21h8s6": ezTt3ayMo,
            "--pgex8v": lschgej4H,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-0nw0H { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Book Open","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-0nw0H");
Icon.displayName = "Book Open";
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    lschgej4H: {
        defaultValue: 1.5,
        displayStepper: true,
        hidden: false,
        max: 6,
        min: 0,
        step: .5,
        title: "Width",
        type: ControlType.Number
    },
    qxTvv_EBh: {
        defaultValue: 0,
        displayStepper: true,
        hidden: false,
        max: 1,
        min: 0,
        step: .1,
        title: "Alpha",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "24",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Book Open\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerVariables": "{\"ezTt3ayMo\":\"color\",\"lschgej4H\":\"width1\",\"qxTvv_EBh\":\"alpha\"}",
                "framerDisableUnlink": "true",
                "framerIntrinsicWidth": "24",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}