// Generated by Framer (98b71dc)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-KUi7X .framer-styles-preset-8m44oq:not(.rich-text-wrapper), .framer-KUi7X .framer-styles-preset-8m44oq.rich-text-wrapper a { --framer-link-hover-text-color: var(--token-6385cab4-00e1-4910-98a9-7e7e0171d88d, #e7e7e8); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-6385cab4-00e1-4910-98a9-7e7e0171d88d, #e7e7e8); --framer-link-text-decoration: none; transition-delay: 0s; transition-duration: 0.2s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }"];
export const className = "framer-KUi7X";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}