// Generated by Framer (504870a)
import siteMetadata from "https://framerusercontent.com/modules/6kFz2jl7ODcknUXsLtcE/AHc0CDOzplFFGI8xZ39W/siteMetadata.js";
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "72rtr7",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "ipa7tz",
            mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"
        }, {
            hash: "1rzm9bk",
            mediaQuery: "(max-width: 809.98px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {
            c0qS96UJJ: "leistungen",
            jDWa1_9hD: "familie-weinek",
            mfmV6neXl: "hero",
            moQ_Dbs8Z: "preise",
            qh_62LL5W: "h\xf6rbeispiele",
            qIWMFBsWY: "hero-container",
            se38XNser: "scroll-trigger",
            WabYJjEVX: "about"
        },
        robots: "max-image-preview:large",
        serializationId: "framer-GOjXB",
        title: siteMetadata(params, activeLocale).title || "Home",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}