// Generated by Framer (f7d95e4)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["iE1w42QNV", "AJjV3kv9o", "WwZM33Did"];
const serializationHash = "framer-sVjZS";
const variantClassNames = {
    AJjV3kv9o: "framer-v-1xcxr9a",
    iE1w42QNV: "framer-v-1to41sr",
    WwZM33Did: "framer-v-1itc88l"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: .2,
    duration: .4,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition2 = {
    delay: .3,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const transition3 = {
    delay: 0,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Step 2": "AJjV3kv9o",
    "Step 3": "WwZM33Did",
    Default: "iE1w42QNV"
};
const getProps = ({
    height,
    id,
    image,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "iE1w42QNV",
        Zz6aodWyw: image ? ? props.Zz6aodWyw ? ? {
            alt: "",
            src: "https://framerusercontent.com/images/Nkp5gY57ncJHhqhfkYGmwMXXftg.png?scale-down-to=1024",
            srcSet: "https://framerusercontent.com/images/Nkp5gY57ncJHhqhfkYGmwMXXftg.png?scale-down-to=512 512w,https://framerusercontent.com/images/Nkp5gY57ncJHhqhfkYGmwMXXftg.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/Nkp5gY57ncJHhqhfkYGmwMXXftg.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/Nkp5gY57ncJHhqhfkYGmwMXXftg.png 2208w"
        }
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        Zz6aodWyw,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "iE1w42QNV",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onAppearkazl76 = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("WwZM33Did", true), 300);
    });
    useOnVariantChange(baseVariant, {
        AJjV3kv9o: onAppearkazl76
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1to41sr", className, classNames),
                    "data-framer-name": "Default",
                    layoutDependency: layoutDependency,
                    layoutId: "iE1w42QNV",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        AJjV3kv9o: {
                            "data-framer-name": "Step 2",
                            "data-highlight": true
                        },
                        WwZM33Did: {
                            "data-framer-name": "Step 3"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-6eldgq",
                        "data-framer-name": "Image Wrap",
                        layoutDependency: layoutDependency,
                        layoutId: "fDy6cHrxq",
                        children: [ /*#__PURE__*/ _jsx(Transition, {
                            value: transition2,
                            children: /*#__PURE__*/ _jsx(Image, {
                                background: {
                                    alt: "",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + ((componentViewport ? .height || 414) * .5000000000000002 - ((componentViewport ? .height || 414) - 0) * 1 / 2) + 0),
                                    sizes: `calc(${(((componentViewport?.height||414)-0)*1-0)*1} * 1.3333)`,
                                    ...toResponsiveImage(Zz6aodWyw)
                                },
                                className: "framer-1jp4k25",
                                layoutDependency: layoutDependency,
                                layoutId: "lBeXiUWf6",
                                style: {
                                    borderBottomLeftRadius: 16,
                                    borderBottomRightRadius: 16,
                                    borderTopLeftRadius: 16,
                                    borderTopRightRadius: 16,
                                    opacity: 0
                                },
                                variants: {
                                    WwZM33Did: {
                                        opacity: 1
                                    }
                                }
                            })
                        }), /*#__PURE__*/ _jsx(Transition, {
                            value: transition3,
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-12rvlsu",
                                "data-framer-name": "Overlay",
                                layoutDependency: layoutDependency,
                                layoutId: "jjXYCJ3gY",
                                style: {
                                    backgroundColor: "var(--token-3baf8a94-a1e8-4d0b-8dbc-4cf79918b4aa, rgb(37, 24, 20))",
                                    borderBottomLeftRadius: 16,
                                    borderBottomRightRadius: 16,
                                    borderTopLeftRadius: 16,
                                    borderTopRightRadius: 16
                                }
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-sVjZS.framer-tjq4dr, .framer-sVjZS .framer-tjq4dr { display: block; }", ".framer-sVjZS.framer-1to41sr { height: 414px; overflow: hidden; position: relative; width: 552px; }", ".framer-sVjZS .framer-6eldgq { flex: none; height: 100%; left: 0px; overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 0%; }", ".framer-sVjZS .framer-1jp4k25 { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: 100%; left: 0px; overflow: visible; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 267px); z-index: 0; }", ".framer-sVjZS .framer-12rvlsu { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: 100%; left: 0px; overflow: hidden; position: absolute; top: 0px; width: var(--framer-aspect-ratio-supported, 267px); will-change: var(--framer-will-change-override, transform); z-index: 1; }", ".framer-sVjZS.framer-v-1xcxr9a .framer-6eldgq, .framer-sVjZS.framer-v-1itc88l .framer-6eldgq { width: 100%; }", ".framer-sVjZS.framer-v-1itc88l .framer-1jp4k25 { z-index: 2; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 414
 * @framerIntrinsicWidth 552
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"AJjV3kv9o":{"layout":["fixed","fixed"]},"WwZM33Did":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"Zz6aodWyw":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerQ1bQ2oEP7 = withCSS(Component, css, "framer-sVjZS");
export default FramerQ1bQ2oEP7;
FramerQ1bQ2oEP7.displayName = "Image Showcase";
FramerQ1bQ2oEP7.defaultProps = {
    height: 414,
    width: 552
};
addPropertyControls(FramerQ1bQ2oEP7, {
    variant: {
        options: ["iE1w42QNV", "AJjV3kv9o", "WwZM33Did"],
        optionTitles: ["Default", "Step 2", "Step 3"],
        title: "Variant",
        type: ControlType.Enum
    },
    Zz6aodWyw: {
        __defaultAssetReference: "data:framer/asset-reference,Nkp5gY57ncJHhqhfkYGmwMXXftg.png?originalFilename=Image+Container.png&preferredSize=auto",
        __vekterDefault: {
            alt: "",
            assetReference: "data:framer/asset-reference,Nkp5gY57ncJHhqhfkYGmwMXXftg.png?originalFilename=Image+Container.png&preferredSize=auto"
        },
        title: "Image",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerQ1bQ2oEP7, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerQ1bQ2oEP7",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "414",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "552",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"AJjV3kv9o\":{\"layout\":[\"fixed\",\"fixed\"]},\"WwZM33Did\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"Zz6aodWyw\":\"image\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./Q1bQ2oEP7.map