// Generated by Framer (62e4d63)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    Container,
    ControlType,
    cx,
    GeneratedComponentContext,
    getFonts,
    getPropertyControls,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX,
    withVariantAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import SmoothScroll from "https://framerusercontent.com/modules/Yppqt3Cs3Y8TZqvASnXl/PGrowqBrgWCViHduGfsA/SmoothScroll_Prod.js";
import Footer from "#framer/local/canvasComponent/BS0pi8Ro6/BS0pi8Ro6.js";
import Cta from "#framer/local/canvasComponent/bxcSYCujy/bxcSYCujy.js";
import MainHeader from "#framer/local/canvasComponent/Lilh5Lcfm/Lilh5Lcfm.js";
const SmoothScrollFonts = getFonts(SmoothScroll);
const MainHeaderFonts = getFonts(MainHeader);
const MainHeaderWithVariantAppearEffect = withVariantAppearEffect(MainHeader);
const ContainerWithFX = withFX(Container);
const CtaFonts = getFonts(Cta);
const FooterFonts = getFonts(Footer);
const MainHeaderControls = getPropertyControls(MainHeader);
const breakpoints = {
    do_Cq78MH: "(max-width: 809.98px)",
    IV7e6Du0i: "(min-width: 1200px)",
    uFQc3Sovr: "(min-width: 810px) and (max-width: 1199.98px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-ftomf";
const variantClassNames = {
    do_Cq78MH: "framer-v-rsp3tt",
    IV7e6Du0i: "framer-v-swpyxt",
    uFQc3Sovr: "framer-v-y5n56r"
};
const transition1 = {
    damping: 40,
    delay: 0,
    mass: 1,
    stiffness: 300,
    type: "spring"
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -120
};
const breakpointRules = {};
const breakpointKeys = Object.keys(breakpointRules);
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ftomf.framer-ge406i, .framer-ftomf .framer-ge406i { display: block; }", ".framer-ftomf.framer-swpyxt { align-content: center; align-items: center; background-color: var(--token-2f87da46-6029-43d9-a3cb-703cb5e84b95, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-ftomf .framer-1fejs26-container { flex: none; height: auto; order: -1000; position: relative; width: auto; }", ".framer-ftomf .framer-1kxrcgk-container { flex: none; height: auto; left: 0px; order: -999; position: var(--framer-canvas-fixed-position, fixed); top: 0px; width: 100%; z-index: 10; }", ".framer-ftomf .framer-1ivsml8 { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-ftomf .framer-1rap9rr-container { flex: none; height: auto; order: 1003; position: relative; width: 100%; }", ".framer-ftomf .framer-tibul5-container { flex: none; height: auto; order: 1004; position: relative; width: 100%; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    do_Cq78MH: "(max-width: 809.98px)",
    IV7e6Du0i: "(min-width: 1200px)",
    uFQc3Sovr: "(min-width: 810px) and (max-width: 1199.98px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableEnumMap = {
    "Other pages": "I3Zzgp6Gt",
    About: "EBFsa0Z_c",
    Blog: "KFn01Hd_B",
    Contact: "bSRLd2UIp",
    Episode: "wIK9gVTpq",
    Home: "P18BwqQoR",
    Host: "b8MybcBpV"
};
const humanReadableVariantMap = {
    Desktop: "IV7e6Du0i",
    Phone: "do_Cq78MH",
    Tablet: "uFQc3Sovr"
};
const getProps = ({
    activePage,
    height,
    id,
    scrollSection,
    width,
    ...props
}) => {
    return { ...props,
        jwZAOvm5T: scrollSection ? ? props.jwZAOvm5T,
        kHD3_8KgG: humanReadableEnumMap[activePage] ? ? activePage ? ? props.kHD3_8KgG ? ? "P18BwqQoR",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "IV7e6Du0i"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        kHD3_8KgG,
        jwZAOvm5T,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "IV7e6Du0i",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-2f87da46-6029-43d9-a3cb-703cb5e84b95, rgb(255, 255, 255)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-swpyxt", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-1fejs26-container",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        nodeId: "wwWmO2PyE",
                        scopeId: "hWVwFQf35",
                        children: /*#__PURE__*/ _jsx(SmoothScroll, {
                            height: "100%",
                            id: "wwWmO2PyE",
                            intensity: 10,
                            layoutId: "wwWmO2PyE",
                            width: "100%"
                        })
                    })
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 106,
                    width: "100vw",
                    y: 0,
                    children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                        __framer__animate: {
                            transition: transition1
                        },
                        __framer__animateOnce: false,
                        __framer__scrollDirection: {
                            direction: "down",
                            target: animation
                        },
                        __framer__styleAppearEffectEnabled: true,
                        __framer__threshold: .5,
                        __perspectiveFX: false,
                        __targetOpacity: 1,
                        className: "framer-1kxrcgk-container",
                        layoutScroll: true,
                        nodeId: "DcyUDuwdF",
                        rendersWithMotion: true,
                        scopeId: "hWVwFQf35",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                do_Cq78MH: {
                                    __framer__targets: [{
                                        ref: jwZAOvm5T,
                                        target: "Sbv_1WzZG"
                                    }],
                                    variant: "MinP1qeYs"
                                },
                                uFQc3Sovr: {
                                    __framer__targets: [{
                                        ref: jwZAOvm5T,
                                        target: "KcEBlWDVn"
                                    }],
                                    variant: "C_XgHeSEa"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(MainHeaderWithVariantAppearEffect, {
                                __framer__animateOnce: false,
                                __framer__targets: [{
                                    ref: jwZAOvm5T,
                                    target: "bxv91Z5ie"
                                }],
                                __framer__threshold: 0,
                                __framer__variantAppearEffectEnabled: true,
                                height: "100%",
                                id: "DcyUDuwdF",
                                layoutId: "DcyUDuwdF",
                                style: {
                                    width: "100%"
                                },
                                variant: "d2f8UdNzN",
                                width: "100%",
                                xftd9927U: kHD3_8KgG
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1ivsml8"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 639,
                    width: "100vw",
                    y: 1200,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-1rap9rr-container",
                        nodeId: "L72QrfNpi",
                        scopeId: "hWVwFQf35",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                do_Cq78MH: {
                                    variant: "XzM5utKJl"
                                },
                                uFQc3Sovr: {
                                    variant: "bgeDF8z46"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Cta, {
                                BXM3FpGP0: "Interesse? Kontakieren Sie uns jederzeit",
                                height: "100%",
                                id: "L72QrfNpi",
                                J4fBHtDxq: "Haben Sie ein Projekt im Kopf, das geh\xf6rt werden soll? Ist noch etwas unklar oder m\xf6chten Sie ein Angebot erhalten? Kontaktieren Sie uns einfach.",
                                layoutId: "L72QrfNpi",
                                style: {
                                    width: "100%"
                                },
                                variant: "BDwS11BkV",
                                width: "100%"
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 548,
                    width: "100vw",
                    y: 1839,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-tibul5-container",
                        nodeId: "FOC6ElIC3",
                        scopeId: "hWVwFQf35",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                do_Cq78MH: {
                                    variant: "RYQ7LjyYT"
                                },
                                uFQc3Sovr: {
                                    variant: "mJeXFr4lA"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                height: "100%",
                                id: "FOC6ElIC3",
                                layoutId: "FOC6ElIC3",
                                style: {
                                    width: "100%"
                                },
                                variant: "fRrCyB8T0",
                                width: "100%"
                            })
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = breakpointRules[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 2600
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"uFQc3Sovr":{"layout":["fixed","fixed"]},"do_Cq78MH":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"kHD3_8KgG":"activePage","jwZAOvm5T":"scrollSection"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"IV7e6Du0i":[".framer-1fejs26-container",".framer-1kxrcgk-container",".framer-1rap9rr-container",".framer-tibul5-container"],"uFQc3Sovr":[".framer-1fejs26-container",".framer-1kxrcgk-container",".framer-1rap9rr-container",".framer-tibul5-container"],"do_Cq78MH":[".framer-1fejs26-container",".framer-1kxrcgk-container",".framer-1rap9rr-container",".framer-tibul5-container"]}
 * @framerBreakpoints {"IV7e6Du0i":{"min":1200,"canvasClassName":"framer-swpyxt-override","minHeight":2600,"name":"Desktop","width":1200,"rootFontSize":16},"uFQc3Sovr":{"min":810,"max":1199,"canvasClassName":"framer-y5n56r-override","minHeight":2600,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"do_Cq78MH":{"max":809,"canvasClassName":"framer-rsp3tt-override","minHeight":2600,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant IV7e6Du0i
 * @framerLayoutTemplate
 */
const FramerhWVwFQf35 = withCSS(Component, css, "framer-ftomf");
export default FramerhWVwFQf35;
FramerhWVwFQf35.displayName = "Main";
FramerhWVwFQf35.defaultProps = {
    height: 2600,
    width: 1200
};
addPropertyControls(FramerhWVwFQf35, {
    kHD3_8KgG: MainHeaderControls ? .["xftd9927U"] && { ...MainHeaderControls["xftd9927U"],
        defaultValue: "P18BwqQoR",
        description: undefined,
        hidden: undefined,
        title: "Active Page"
    },
    jwZAOvm5T: {
        title: "Scroll Section",
        type: ControlType.ScrollSectionRef
    }
});
addFonts(FramerhWVwFQf35, [{
    explicitInter: true,
    fonts: []
}, ...SmoothScrollFonts, ...MainHeaderFonts, ...CtaFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerhWVwFQf35",
            "slots": [],
            "annotations": {
                "framerLayoutTemplate": "",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "2600",
                "framerHitTargets": "{\"IV7e6Du0i\":[\".framer-1fejs26-container\",\".framer-1kxrcgk-container\",\".framer-1rap9rr-container\",\".framer-tibul5-container\"],\"uFQc3Sovr\":[\".framer-1fejs26-container\",\".framer-1kxrcgk-container\",\".framer-1rap9rr-container\",\".framer-tibul5-container\"],\"do_Cq78MH\":[\".framer-1fejs26-container\",\".framer-1kxrcgk-container\",\".framer-1rap9rr-container\",\".framer-tibul5-container\"]}",
                "framerDefaultVariant": "IV7e6Du0i",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"uFQc3Sovr\":{\"layout\":[\"fixed\",\"fixed\"]},\"do_Cq78MH\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerBreakpoints": "{\"IV7e6Du0i\":{\"min\":1200,\"canvasClassName\":\"framer-swpyxt-override\",\"minHeight\":2600,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"uFQc3Sovr\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-y5n56r-override\",\"minHeight\":2600,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"do_Cq78MH\":{\"max\":809,\"canvasClassName\":\"framer-rsp3tt-override\",\"minHeight\":2600,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"kHD3_8KgG\":\"activePage\",\"jwZAOvm5T\":\"scrollSection\"}",
                "framerIntrinsicWidth": "1200"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}