// Generated by Framer (f7d95e4)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    Container,
    ControlType,
    cx,
    GeneratedComponentContext,
    getFonts,
    getPropertyControls,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX,
    withVariantAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import SmoothScroll from "https://framerusercontent.com/modules/Yppqt3Cs3Y8TZqvASnXl/PGrowqBrgWCViHduGfsA/SmoothScroll_Prod.js";
import Footer from "#framer/local/canvasComponent/BS0pi8Ro6/BS0pi8Ro6.js";
import Cta from "#framer/local/canvasComponent/bxcSYCujy/bxcSYCujy.js";
import MainHeader from "#framer/local/canvasComponent/Lilh5Lcfm/Lilh5Lcfm.js";
const SmoothScrollFonts = getFonts(SmoothScroll);
const MainHeaderFonts = getFonts(MainHeader);
const MainHeaderWithVariantAppearEffect = withVariantAppearEffect(MainHeader);
const ContainerWithFX = withFX(Container);
const CtaFonts = getFonts(Cta);
const FooterFonts = getFonts(Footer);
const MainHeaderControls = getPropertyControls(MainHeader);
const breakpoints = {
    BUwV9QAh3: "(min-width: 810px) and (max-width: 1199px)",
    pFLd49T06: "(max-width: 809px)",
    RtqMsWCTj: "(min-width: 1200px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-QiRxX";
const variantClassNames = {
    BUwV9QAh3: "framer-v-15vsxm0",
    pFLd49T06: "framer-v-zshop1",
    RtqMsWCTj: "framer-v-1huaa1q"
};
const transition1 = {
    damping: 40,
    delay: 0,
    mass: 1,
    stiffness: 300,
    type: "spring"
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -120
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const breakpointRules = {
    BUwV9QAh3: [".framer-QiRxX .framer-1jpplxt-container { left: 50%; position: absolute; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    BUwV9QAh3: ".framer-15vsxm0-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-QiRxX.framer-1emvq0x, .framer-QiRxX .framer-1emvq0x { display: block; }", ".framer-QiRxX.framer-1huaa1q { align-content: center; align-items: center; background-color: var(--token-2f87da46-6029-43d9-a3cb-703cb5e84b95, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-QiRxX .framer-liues3-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-QiRxX .framer-1jpplxt-container { flex: none; height: auto; left: 0px; position: var(--framer-canvas-fixed-position, fixed); top: 0px; width: 100%; z-index: 10; }", ".framer-QiRxX .framer-1hhu3kg { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: calc(0 * -1px); position: relative; width: 0px; }", ".framer-QiRxX .framer-wk8kz1-container { flex: none; height: auto; order: 1003; position: relative; width: 100%; }", ".framer-QiRxX .framer-h59itm-container { flex: none; height: auto; order: 1004; position: relative; width: 100%; }", '[data-layout-template="true"] > #overlay { margin-bottom: calc(0 * -1px); }', "@supports (background: -webkit-named-image(i)) and (not (scale:1)) { .framer-QiRxX.framer-1huaa1q { gap: 0px; } .framer-QiRxX.framer-1huaa1q > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-QiRxX.framer-1huaa1q > :first-child { margin-top: 0px; } .framer-QiRxX.framer-1huaa1q > :last-child { margin-bottom: 0px; } }"];
const mediaQueries = {
    BUwV9QAh3: "(min-width: 810px) and (max-width: 1199px)",
    pFLd49T06: "(max-width: 809px)",
    RtqMsWCTj: "(min-width: 1200px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableEnumMap = {
    "Other pages": "I3Zzgp6Gt",
    About: "EBFsa0Z_c",
    Blog: "KFn01Hd_B",
    Contact: "bSRLd2UIp",
    Episode: "wIK9gVTpq",
    Home: "P18BwqQoR",
    Host: "b8MybcBpV"
};
const humanReadableVariantMap = {
    Desktop: "RtqMsWCTj",
    Phone: "pFLd49T06",
    Tablet: "BUwV9QAh3"
};
const getProps = ({
    activePage,
    height,
    id,
    scrollSection,
    width,
    ...props
}) => {
    return { ...props,
        jwZAOvm5T: scrollSection ? ? props.jwZAOvm5T,
        kHD3_8KgG: humanReadableEnumMap[activePage] ? ? activePage ? ? props.kHD3_8KgG ? ? "P18BwqQoR",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "RtqMsWCTj"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        kHD3_8KgG,
        jwZAOvm5T,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "RtqMsWCTj",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-2f87da46-6029-43d9-a3cb-703cb5e84b95, rgb(255, 255, 255)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-1huaa1q", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-liues3-container",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        nodeId: "VhLkuVDVz",
                        scopeId: "Fwt_jmEkb",
                        children: /*#__PURE__*/ _jsx(SmoothScroll, {
                            height: "100%",
                            id: "VhLkuVDVz",
                            intensity: 10,
                            layoutId: "VhLkuVDVz",
                            width: "100%"
                        })
                    })
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 96,
                    width: "100vw",
                    y: 0,
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                            BUwV9QAh3: {
                                "data-framer-layout-hint-center-x": true,
                                transformTemplate: transformTemplate1
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                            __framer__animate: {
                                transition: transition1
                            },
                            __framer__animateOnce: false,
                            __framer__scrollDirection: {
                                direction: "down",
                                target: animation
                            },
                            __framer__styleAppearEffectEnabled: true,
                            __framer__threshold: .5,
                            __perspectiveFX: false,
                            __targetOpacity: 1,
                            className: "framer-1jpplxt-container",
                            layoutScroll: true,
                            nodeId: "g0MKwdAxO",
                            rendersWithMotion: true,
                            scopeId: "Fwt_jmEkb",
                            children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                    BUwV9QAh3: {
                                        __framer__targets: [{
                                            ref: jwZAOvm5T,
                                            target: "KcEBlWDVn"
                                        }],
                                        variant: "KcEBlWDVn"
                                    },
                                    pFLd49T06: {
                                        __framer__targets: [{
                                            ref: jwZAOvm5T,
                                            target: "Sbv_1WzZG"
                                        }],
                                        variant: "Sbv_1WzZG"
                                    }
                                },
                                children: /*#__PURE__*/ _jsx(MainHeaderWithVariantAppearEffect, {
                                    __framer__animateOnce: false,
                                    __framer__targets: [{
                                        ref: jwZAOvm5T,
                                        target: "bxv91Z5ie"
                                    }],
                                    __framer__threshold: 0,
                                    __framer__variantAppearEffectEnabled: true,
                                    height: "100%",
                                    id: "g0MKwdAxO",
                                    layoutId: "g0MKwdAxO",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "X15yt3ES5",
                                    width: "100%",
                                    xftd9927U: kHD3_8KgG
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1hhu3kg"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 637,
                    width: "100vw",
                    y: 1200,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-wk8kz1-container",
                        nodeId: "XPuepEt5x",
                        scopeId: "Fwt_jmEkb",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                BUwV9QAh3: {
                                    variant: "bgeDF8z46"
                                },
                                pFLd49T06: {
                                    variant: "XzM5utKJl"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Cta, {
                                height: "100%",
                                id: "XPuepEt5x",
                                iG3d2VxWh: false,
                                layoutId: "XPuepEt5x",
                                style: {
                                    width: "100%"
                                },
                                variant: "BDwS11BkV",
                                width: "100%"
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 548,
                    width: "100vw",
                    y: 1837,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-h59itm-container",
                        nodeId: "ZvWASJHUg",
                        scopeId: "Fwt_jmEkb",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                BUwV9QAh3: {
                                    variant: "mJeXFr4lA"
                                },
                                pFLd49T06: {
                                    variant: "RYQ7LjyYT"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                height: "100%",
                                id: "ZvWASJHUg",
                                layoutId: "ZvWASJHUg",
                                style: {
                                    width: "100%"
                                },
                                variant: "fRrCyB8T0",
                                width: "100%"
                            })
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 2600
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"BUwV9QAh3":{"layout":["fixed","fixed"]},"pFLd49T06":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"kHD3_8KgG":"activePage","jwZAOvm5T":"scrollSection"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 * @framerHitTargets {"RtqMsWCTj":[".framer-liues3-container",".framer-1jpplxt-container",".framer-wk8kz1-container",".framer-h59itm-container"],"BUwV9QAh3":[".framer-liues3-container",".framer-1jpplxt-container",".framer-wk8kz1-container",".framer-h59itm-container"],"pFLd49T06":[".framer-liues3-container",".framer-1jpplxt-container",".framer-wk8kz1-container",".framer-h59itm-container"]}
 * @framerBreakpoints {"RtqMsWCTj":{"min":1200,"canvasClassName":"framer-1huaa1q-override","minHeight":2600,"name":"Desktop","width":1200},"BUwV9QAh3":{"min":810,"max":1199,"canvasClassName":"framer-15vsxm0-override","minHeight":2600,"viewportHeight":1080,"name":"Tablet","width":810},"pFLd49T06":{"max":809,"canvasClassName":"framer-zshop1-override","minHeight":2600,"viewportHeight":844,"name":"Phone","width":390}}
 * @framerDefaultVariant RtqMsWCTj
 * @framerLayoutTemplate
 */
const FramerFwt_jmEkb = withCSS(Component, css, "framer-QiRxX");
export default FramerFwt_jmEkb;
FramerFwt_jmEkb.displayName = "Secondary";
FramerFwt_jmEkb.defaultProps = {
    height: 2600,
    width: 1200
};
addPropertyControls(FramerFwt_jmEkb, {
    kHD3_8KgG: MainHeaderControls ? .["xftd9927U"] && { ...MainHeaderControls["xftd9927U"],
        defaultValue: "P18BwqQoR",
        description: undefined,
        hidden: undefined,
        title: "Active Page"
    },
    jwZAOvm5T: {
        title: "Scroll Section",
        type: ControlType.ScrollSectionRef
    }
});
addFonts(FramerFwt_jmEkb, [{
    explicitInter: true,
    fonts: []
}, ...SmoothScrollFonts, ...MainHeaderFonts, ...CtaFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerFwt_jmEkb",
            "slots": [],
            "annotations": {
                "framerLayoutTemplate": "",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"BUwV9QAh3\":{\"layout\":[\"fixed\",\"fixed\"]},\"pFLd49T06\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicHeight": "2600",
                "framerDisplayContentsDiv": "false",
                "framerDefaultVariant": "RtqMsWCTj",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "1200",
                "framerContractVersion": "1",
                "framerHitTargets": "{\"RtqMsWCTj\":[\".framer-liues3-container\",\".framer-1jpplxt-container\",\".framer-wk8kz1-container\",\".framer-h59itm-container\"],\"BUwV9QAh3\":[\".framer-liues3-container\",\".framer-1jpplxt-container\",\".framer-wk8kz1-container\",\".framer-h59itm-container\"],\"pFLd49T06\":[\".framer-liues3-container\",\".framer-1jpplxt-container\",\".framer-wk8kz1-container\",\".framer-h59itm-container\"]}",
                "framerBreakpoints": "{\"RtqMsWCTj\":{\"min\":1200,\"canvasClassName\":\"framer-1huaa1q-override\",\"minHeight\":2600,\"name\":\"Desktop\",\"width\":1200},\"BUwV9QAh3\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-15vsxm0-override\",\"minHeight\":2600,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810},\"pFLd49T06\":{\"max\":809,\"canvasClassName\":\"framer-zshop1-override\",\"minHeight\":2600,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390}}",
                "framerVariables": "{\"kHD3_8KgG\":\"activePage\",\"jwZAOvm5T\":\"scrollSection\"}",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}