// Generated by Framer (8c7c84e)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as t,
    QueryEngine as r
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as i
} from "./ts8ypJfAD-0.js";
import {
    getRichTextJsonResolver as o
} from "./ts8ypJfAD-1.js";
let m = {
        a_vtEiILk: {
            isNullable: !0,
            type: l.String
        },
        a7hIxpZ1U: {
            isNullable: !0,
            type: l.String
        },
        axmV5xkfz: {
            isNullable: !0,
            type: l.RichText
        },
        b67guB59O: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        DB7qxWdIr: {
            isNullable: !0,
            type: l.String
        },
        E_4OLzwPq: {
            isNullable: !0,
            type: l.String
        },
        eWyT1Kgcj: {
            isNullable: !0,
            type: l.File
        },
        fKyXIGKVj: {
            isNullable: !0,
            type: l.String
        },
        G4iIQFqM9: {
            definition: {
                isNullable: !0,
                type: l.String
            },
            isNullable: !0,
            type: l.Array
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        kr6mh8_3g: {
            definition: {
                isNullable: !0,
                type: l.String
            },
            isNullable: !0,
            type: l.Array
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        OX2qQb_uZ: {
            isNullable: !0,
            type: l.String
        },
        p4k_NUiy9: {
            isNullable: !0,
            type: l.RichText
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        qodlPL7Hv: {
            isNullable: !0,
            type: l.Date
        },
        RCHQJr26t: {
            isNullable: !0,
            type: l.File
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        Vk_GMoklP: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        vrrzGfIzE: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        WZn8tJRW2: {
            isNullable: !0,
            type: l.Link
        }
    },
    n = ["id"],
    c = {
        type: 1
    },
    s = ["previousItemId"],
    f = ["nextItemId"],
    u = ["id", "DB7qxWdIr"],
    d = ["DB7qxWdIr", "id"],
    p = ["DB7qxWdIr"],
    y = {
        type: 0
    },
    g = ["fKyXIGKVj"],
    h = ["qodlPL7Hv"],
    w = ["a_vtEiILk"],
    x = ["b67guB59O"],
    I = ["OX2qQb_uZ"],
    N = ["eWyT1Kgcj"],
    D = ["E_4OLzwPq"],
    R = ["G4iIQFqM9"],
    S = ["RCHQJr26t"],
    L = ["Vk_GMoklP"],
    A = ["vrrzGfIzE"],
    J = ["a7hIxpZ1U"],
    b = ["kr6mh8_3g"],
    U = ["WZn8tJRW2"],
    k = ["axmV5xkfz"],
    V = ["p4k_NUiy9"],
    q = [],
    v = e => {
        let l = q[e];
        if (l) return l().then(e => e.default);
    },
    W = {},
    _ = o(W),
    C = new r,
    B = new t(C),
    T = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./ts8ypJfAD-chunk-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")],
                indexes: [new i({
                    collation: c,
                    collectionSchema: m,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 121
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: m,
                    fieldNames: s,
                    range: {
                        from: 121,
                        to: 241
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: m,
                    fieldNames: f,
                    range: {
                        from: 241,
                        to: 357
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: m,
                    fieldNames: u,
                    range: {
                        from: 357,
                        to: 637
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: m,
                    fieldNames: d,
                    range: {
                        from: 637,
                        to: 917
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: p,
                    range: {
                        from: 917,
                        to: 1135
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: g,
                    range: {
                        from: 1135,
                        to: 1353
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: h,
                    range: {
                        from: 1353,
                        to: 1461
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: w,
                    range: {
                        from: 1461,
                        to: 1601
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: x,
                    range: {
                        from: 1601,
                        to: 1709
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: I,
                    range: {
                        from: 1709,
                        to: 1837
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: N,
                    range: {
                        from: 1837,
                        to: 2201
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: D,
                    range: {
                        from: 2201,
                        to: 2329
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: R,
                    range: {
                        from: 2329,
                        to: 2469
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: S,
                    range: {
                        from: 2469,
                        to: 2829
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: L,
                    range: {
                        from: 2829,
                        to: 5849
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: A,
                    range: {
                        from: 5849,
                        to: 8905
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: J,
                    range: {
                        from: 8905,
                        to: 9445
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: b,
                    range: {
                        from: 9445,
                        to: 9641
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: U,
                    range: {
                        from: 9641,
                        to: 9853
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: k,
                    range: {
                        from: 9853,
                        to: 13133
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: m,
                    fieldNames: V,
                    range: {
                        from: 13133,
                        to: 14897
                    },
                    url: new URL("./ts8ypJfAD-indexes-default-0.framercms", "https://framerusercontent.com/modules/fBK3RZpYnMod0cqjPyJn/AcwADk0RaAReQN8niq5m/ts8ypJfAD.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: _,
                resolveVectorSetItem: v,
                schema: m
            })
        },
        displayName: "H\xf6rproben"
    };
export default T;
e(T, {
    DB7qxWdIr: {
        title: "Slug",
        type: l.String
    },
    fKyXIGKVj: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    qodlPL7Hv: {
        title: "Datum",
        type: l.Date
    },
    a_vtEiILk: {
        defaultValue: "",
        title: "Duration",
        type: l.String
    },
    b67guB59O: {
        defaultValue: "",
        title: "Kunde",
        type: l.String
    },
    OX2qQb_uZ: {
        defaultValue: "",
        title: "Category Text",
        type: l.String
    },
    eWyT1Kgcj: {
        allowedFileTypes: ["mp3"],
        title: "MP3",
        type: l.File
    },
    E_4OLzwPq: {
        dataIdentifier: "local-module:collection/VlAUTYqCz:default",
        title: "Person",
        type: l.CollectionReference
    },
    G4iIQFqM9: {
        dataIdentifier: "local-module:collection/CTYsJ63NV:default",
        title: "Podcast Categories",
        type: l.MultiCollectionReference
    },
    RCHQJr26t: {
        allowedFileTypes: ["mp4"],
        title: "File",
        type: l.File
    },
    Vk_GMoklP: {
        title: "Thumbnail Image",
        type: l.ResponsiveImage
    },
    vrrzGfIzE: {
        title: "Video Thumbnail Image",
        type: l.ResponsiveImage
    },
    a7hIxpZ1U: {
        defaultValue: "",
        title: "Quote",
        type: l.String
    },
    kr6mh8_3g: {
        dataIdentifier: "local-module:collection/WQO73dS8G:default",
        title: "Guests",
        type: l.MultiCollectionReference
    },
    WZn8tJRW2: {
        title: "Podcast Link",
        type: l.Link
    },
    axmV5xkfz: {
        defaultValue: "",
        title: "Content",
        type: l.RichText
    },
    p4k_NUiy9: {
        defaultValue: "",
        title: "Content 2",
        type: l.RichText
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/ts8ypJfAD:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/ts8ypJfAD:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await B.get({
            from: {
                data: T,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "DB7qxWdIr",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .DB7qxWdIr;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await B.get({
            from: {
                data: T,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "DB7qxWdIr",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerCollectionUtils": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerSlug": "DB7qxWdIr",
                "framerRecordIdKey": "id",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerCollectionId": "ts8ypJfAD",
                "framerData": "",
                "framerColorSyntax": "false"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}