// Generated by Framer (2abc263)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["Kzo5F4xgu", "A323G8VuA"];
const serializationHash = "framer-VoemN";
const variantClassNames = {
    A323G8VuA: "framer-v-ixo47f",
    Kzo5F4xgu: "framer-v-1khvj0m"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 30,
    delay: 0,
    mass: 1,
    stiffness: 400,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Burger: "Kzo5F4xgu",
    X: "A323G8VuA"
};
const getProps = ({
    color,
    height,
    id,
    tap,
    width,
    ...props
}) => {
    return { ...props,
        iWF8EWIN1: color ? ? props.iWF8EWIN1 ? ? "var(--token-3eeeadcf-7a3a-42f2-9a6c-47f4d4eb10dd, rgb(78, 82, 85))",
        TBgHLr7MW: tap ? ? props.TBgHLr7MW,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "Kzo5F4xgu"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        TBgHLr7MW,
        iWF8EWIN1,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "Kzo5F4xgu",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1nvfyws = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (TBgHLr7MW) {
            const res = await TBgHLr7MW(...args);
            if (res === false) return false;
        }
        setVariant("A323G8VuA");
    });
    const onTapzl1zbi = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (TBgHLr7MW) {
            const res = await TBgHLr7MW(...args);
            if (res === false) return false;
        }
        setVariant("Kzo5F4xgu");
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1khvj0m", className, classNames),
                    "data-framer-name": "Burger",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "Kzo5F4xgu",
                    onTap: onTap1nvfyws,
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        A323G8VuA: {
                            "data-framer-name": "X",
                            onTap: onTapzl1zbi
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ythi55",
                        layoutDependency: layoutDependency,
                        layoutId: "NsRiIqAHJ",
                        children: [ /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-36xcjk",
                            "data-framer-name": "Bottom",
                            layoutDependency: layoutDependency,
                            layoutId: "kwiiwMZPW",
                            style: {
                                backgroundColor: iWF8EWIN1,
                                rotate: 0
                            },
                            variants: {
                                A323G8VuA: {
                                    rotate: -45
                                }
                            }
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-1arc290",
                            "data-framer-name": "Mid",
                            layoutDependency: layoutDependency,
                            layoutId: "B2sIJwvLj",
                            style: {
                                backgroundColor: iWF8EWIN1,
                                opacity: 1
                            },
                            variants: {
                                A323G8VuA: {
                                    opacity: 0
                                }
                            }
                        }), /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-8gbntk",
                            "data-framer-name": "Top",
                            layoutDependency: layoutDependency,
                            layoutId: "J1BIfesfq",
                            style: {
                                backgroundColor: iWF8EWIN1,
                                rotate: 0
                            },
                            variants: {
                                A323G8VuA: {
                                    rotate: 45
                                }
                            }
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-VoemN.framer-1jeu1qk, .framer-VoemN .framer-1jeu1qk { display: block; }", ".framer-VoemN.framer-1khvj0m { cursor: pointer; height: 32px; overflow: hidden; position: relative; width: 32px; }", ".framer-VoemN .framer-ythi55 { flex: none; height: 18px; left: calc(50.00000000000002% - 24px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 18px / 2); width: 24px; }", ".framer-VoemN .framer-36xcjk { bottom: 0px; flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; }", ".framer-VoemN .framer-1arc290 { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: calc(50.00000000000002% - 2px / 2); }", ".framer-VoemN .framer-8gbntk { flex: none; height: 2px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }", ".framer-VoemN.framer-v-ixo47f .framer-36xcjk { bottom: unset; top: calc(50.00000000000002% - 2px / 2); }", ".framer-VoemN.framer-v-ixo47f .framer-1arc290 { left: unset; width: 2px; }", ".framer-VoemN.framer-v-ixo47f .framer-8gbntk { top: calc(50.00000000000002% - 2px / 2); }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"A323G8VuA":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"TBgHLr7MW":"tap","iWF8EWIN1":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramererMrXWZNJ = withCSS(Component, css, "framer-VoemN");
export default FramererMrXWZNJ;
FramererMrXWZNJ.displayName = "Menu Icon";
FramererMrXWZNJ.defaultProps = {
    height: 32,
    width: 32
};
addPropertyControls(FramererMrXWZNJ, {
    variant: {
        options: ["Kzo5F4xgu", "A323G8VuA"],
        optionTitles: ["Burger", "X"],
        title: "Variant",
        type: ControlType.Enum
    },
    TBgHLr7MW: {
        title: "Tap",
        type: ControlType.EventHandler
    },
    iWF8EWIN1: {
        defaultValue: 'var(--token-3eeeadcf-7a3a-42f2-9a6c-47f4d4eb10dd, rgb(78, 82, 85)) /* {"name":"General Paragraph"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(FramererMrXWZNJ, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramererMrXWZNJ",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"A323G8VuA\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "32",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"TBgHLr7MW\":\"tap\",\"iWF8EWIN1\":\"color\"}",
                "framerIntrinsicHeight": "32"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./erMrXWZNJ.map