// Generated by Framer (869144b)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as t,
    QueryEngine as a
} from "framer";
import {
    DatabaseCollection as r,
    DatabaseDictionaryIndex as i
} from "./VlAUTYqCz-0.js";
import {
    getRichTextJsonResolver as m
} from "./VlAUTYqCz-1.js";
let o = {
        ambKga5Fk: {
            isNullable: !0,
            type: l.String
        },
        aRzGgtvqa: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        D9QGivR60: {
            isNullable: !0,
            type: l.String
        },
        dB_TRlt68: {
            isNullable: !0,
            type: l.Link
        },
        DkEt1QE_0: {
            isNullable: !0,
            type: l.String
        },
        eQ7iMcFIy: {
            isNullable: !0,
            type: l.String
        },
        fHqkviQ2q: {
            isNullable: !0,
            type: l.Link
        },
        hHyvrFxYG: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        JQ5_e5FRt: {
            isNullable: !0,
            type: l.Link
        },
        lWpGUmwQh: {
            isNullable: !0,
            type: l.Link
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        nZ9LBJHje: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        sNR8ZBoQ6: {
            isNullable: !0,
            type: l.Link
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        yyEzLFGW2: {
            isNullable: !0,
            type: l.String
        }
    },
    n = ["id"],
    c = {
        type: 1
    },
    s = ["previousItemId"],
    u = ["nextItemId"],
    d = ["id", "D9QGivR60"],
    f = ["D9QGivR60", "id"],
    p = ["D9QGivR60"],
    y = {
        type: 0
    },
    g = ["ambKga5Fk"],
    h = ["aRzGgtvqa"],
    w = ["eQ7iMcFIy"],
    R = ["DkEt1QE_0"],
    L = ["yyEzLFGW2"],
    U = ["nZ9LBJHje"],
    N = ["hHyvrFxYG"],
    S = ["lWpGUmwQh"],
    q = ["dB_TRlt68"],
    V = ["fHqkviQ2q"],
    T = ["JQ5_e5FRt"],
    v = ["sNR8ZBoQ6"],
    I = [],
    x = e => {
        let l = I[e];
        if (l) return l().then(e => e.default);
    },
    z = {},
    A = m(z),
    C = new a,
    k = new t(C),
    Q = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./VlAUTYqCz-chunk-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")],
                indexes: [new i({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 145
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: s,
                    range: {
                        from: 145,
                        to: 289
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: u,
                    range: {
                        from: 289,
                        to: 429
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: d,
                    range: {
                        from: 429,
                        to: 674
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: c,
                    collectionSchema: o,
                    fieldNames: f,
                    range: {
                        from: 674,
                        to: 919
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: p,
                    range: {
                        from: 919,
                        to: 1088
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: g,
                    range: {
                        from: 1088,
                        to: 1257
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: h,
                    range: {
                        from: 1257,
                        to: 1478
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: w,
                    range: {
                        from: 1478,
                        to: 1769
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: R,
                    range: {
                        from: 1769,
                        to: 1931
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: L,
                    range: {
                        from: 1931,
                        to: 2809
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: U,
                    range: {
                        from: 2809,
                        to: 4810
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: N,
                    range: {
                        from: 4810,
                        to: 7392
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: S,
                    range: {
                        from: 7392,
                        to: 7574
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: q,
                    range: {
                        from: 7574,
                        to: 7716
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: V,
                    range: {
                        from: 7716,
                        to: 7893
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: T,
                    range: {
                        from: 7893,
                        to: 8070
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                }), new i({
                    collation: y,
                    collectionSchema: o,
                    fieldNames: v,
                    range: {
                        from: 8070,
                        to: 8237
                    },
                    url: new URL("./VlAUTYqCz-indexes-default-0.framercms", "https://framerusercontent.com/modules/2UJKIJcrO5dZf1pQFCKD/WPYsrDobksoEbLGyu9Rn/VlAUTYqCz.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: A,
                resolveVectorSetItem: x,
                schema: o
            })
        },
        displayName: "Familienmitglieder"
    };
export default Q;
e(Q, {
    D9QGivR60: {
        title: "Slug",
        type: l.String
    },
    ambKga5Fk: {
        defaultValue: "",
        title: "Name",
        type: l.String
    },
    aRzGgtvqa: {
        defaultValue: "",
        title: "Designation",
        type: l.String
    },
    eQ7iMcFIy: {
        defaultValue: "",
        title: "Detailed Designation",
        type: l.String
    },
    DkEt1QE_0: {
        defaultValue: "",
        title: "Total Coverd Topics",
        type: l.String
    },
    yyEzLFGW2: {
        defaultValue: "",
        title: "Short Description",
        type: l.String
    },
    nZ9LBJHje: {
        title: "Host Image",
        type: l.ResponsiveImage
    },
    hHyvrFxYG: {
        title: "Host Details image",
        type: l.ResponsiveImage
    },
    lWpGUmwQh: {
        title: "Instagram Link",
        type: l.Link
    },
    dB_TRlt68: {
        title: "Twitter Link",
        type: l.Link
    },
    fHqkviQ2q: {
        title: "Facebook Link",
        type: l.Link
    },
    JQ5_e5FRt: {
        title: "Linkedin Link",
        type: l.Link
    },
    sNR8ZBoQ6: {
        title: "Thread Link",
        type: l.Link
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/VlAUTYqCz:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/VlAUTYqCz:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await k.get({
            from: {
                data: Q,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "D9QGivR60",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .D9QGivR60;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await k.get({
            from: {
                data: Q,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "D9QGivR60",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerData": "",
                "framerEnumToDisplayNameUtils": "2",
                "framerSlug": "D9QGivR60",
                "framerCollectionId": "VlAUTYqCz",
                "framerContractVersion": "1",
                "framerColorSyntax": "false",
                "framerRecordIdKey": "id",
                "framerAutoSizeImages": "true",
                "framerCollectionUtils": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}