// Generated by Framer (128ce9c)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    Link,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const enabledGestures = {
    RQUjnKQR1: {
        hover: true
    }
};
const cycleOrder = ["RQUjnKQR1", "ppdCLcJVB"];
const serializationHash = "framer-hoiwr";
const variantClassNames = {
    ppdCLcJVB: "framer-v-1qh3okq",
    RQUjnKQR1: "framer-v-18gku3r"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .4,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "RQUjnKQR1",
    Phone: "ppdCLcJVB"
};
const getProps = ({
    height,
    icon,
    id,
    link,
    width,
    ...props
}) => {
    return { ...props,
        h1SUSpIu4: icon ? ? props.h1SUSpIu4 ? ? {
            alt: "Social Icon",
            pixelHeight: 50,
            pixelWidth: 50,
            src: "https://framerusercontent.com/images/WFFAVEeJQxDrI8M6vbpYAcc5P8.svg"
        },
        mnMotG9I7: link ? ? props.mnMotG9I7,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "RQUjnKQR1"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        h1SUSpIu4,
        mnMotG9I7,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "RQUjnKQR1",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: mnMotG9I7,
                    motionChild: true,
                    nodeId: "RQUjnKQR1",
                    scopeId: "HfOMBkYD8",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-18gku3r",className,classNames)} framer-1rdteg0`,
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "RQUjnKQR1",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "RQUjnKQR1-hover": {
                                "data-framer-name": undefined
                            },
                            ppdCLcJVB: {
                                "data-framer-name": "Phone"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(Image, {
                            background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + 0),
                                pixelHeight: 50,
                                pixelWidth: 50,
                                sizes: componentViewport ? .width || "100vw",
                                ...toResponsiveImage(h1SUSpIu4)
                            },
                            className: "framer-10axmde",
                            "data-framer-name": "Icon",
                            layoutDependency: layoutDependency,
                            layoutId: "Hzpoutr2O",
                            style: {
                                scale: 1
                            },
                            variants: {
                                "RQUjnKQR1-hover": {
                                    scale: 1.04
                                }
                            }
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-hoiwr.framer-1rdteg0, .framer-hoiwr .framer-1rdteg0 { display: block; }", ".framer-hoiwr.framer-18gku3r { cursor: pointer; height: 44px; overflow: visible; position: relative; text-decoration: none; width: 44px; }", ".framer-hoiwr .framer-10axmde { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }", ".framer-hoiwr.framer-v-1qh3okq.framer-18gku3r { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 30px); width: 30px; }", ".framer-hoiwr.framer-v-1qh3okq .framer-10axmde { height: var(--framer-aspect-ratio-supported, 30px); }", ".framer-hoiwr.framer-v-18gku3r.hover.framer-18gku3r { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 44px); }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 44
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"ppdCLcJVB":{"layout":["fixed","fixed"]},"UZ6mizg9p":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"h1SUSpIu4":"icon","mnMotG9I7":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerHfOMBkYD8 = withCSS(Component, css, "framer-hoiwr");
export default FramerHfOMBkYD8;
FramerHfOMBkYD8.displayName = "Social Icon";
FramerHfOMBkYD8.defaultProps = {
    height: 44,
    width: 44
};
addPropertyControls(FramerHfOMBkYD8, {
    variant: {
        options: ["RQUjnKQR1", "ppdCLcJVB"],
        optionTitles: ["Default", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    h1SUSpIu4: {
        __defaultAssetReference: "data:framer/asset-reference,WFFAVEeJQxDrI8M6vbpYAcc5P8.svg?originalFilename=Google+Podcast.svg&preferredSize=auto",
        __vekterDefault: {
            alt: "Social Icon",
            assetReference: "data:framer/asset-reference,WFFAVEeJQxDrI8M6vbpYAcc5P8.svg?originalFilename=Google+Podcast.svg&preferredSize=auto"
        },
        title: "Icon",
        type: ControlType.ResponsiveImage
    },
    mnMotG9I7: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerHfOMBkYD8, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerHfOMBkYD8",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"h1SUSpIu4\":\"icon\",\"mnMotG9I7\":\"link\"}",
                "framerIntrinsicHeight": "44",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"ppdCLcJVB\":{\"layout\":[\"fixed\",\"fixed\"]},\"UZ6mizg9p\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerIntrinsicWidth": "44",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./HfOMBkYD8.map